# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

monte_carlo_up_and_in_put <- function(S0, K, t, r, sigma, b, N = 10000L) {
    .Call(`_mcOptionPricer_monte_carlo_up_and_in_put`, S0, K, t, r, sigma, b, N)
}

rcpp_hello_world <- function() {
    .Call(`_mcOptionPricer_rcpp_hello_world`)
}

